#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadNeuseCSV
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="nssnc")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertsection(section instance);
    partial void Updatesection(section instance);
    partial void Deletesection(section instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::LoadNeuseCSV.Properties.Settings.Default.nssncConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<section> sections
		{
			get
			{
				return this.GetTable<section>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sections")]
	public partial class section : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sectionID;
		
		private string _sectionName;
		
		private string _sectionName2;
		
		private string _sectionName3;
		
		private string _sectionWorkingName;
		
		private string _sectionImage;
		
		private System.Nullable<int> _topSection;
		
		private System.Nullable<int> _sectionOrder;
		
		private System.Nullable<byte> _rootSection;
		
		private System.Nullable<byte> _sectionDisabled;
		
		private string _sectionurl;
		
		private string _sectionurl2;
		
		private string _sectionurl3;
		
		private string _sectionHeader;
		
		private string _sectionHeader2;
		
		private string _sectionHeader3;
		
		private string _sectionDescription;
		
		private string _sectionDescription2;
		
		private string _sectionDescription3;
		
		private string _sTitle;
		
		private string _sMetaDesc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsectionIDChanging(int value);
    partial void OnsectionIDChanged();
    partial void OnsectionNameChanging(string value);
    partial void OnsectionNameChanged();
    partial void OnsectionName2Changing(string value);
    partial void OnsectionName2Changed();
    partial void OnsectionName3Changing(string value);
    partial void OnsectionName3Changed();
    partial void OnsectionWorkingNameChanging(string value);
    partial void OnsectionWorkingNameChanged();
    partial void OnsectionImageChanging(string value);
    partial void OnsectionImageChanged();
    partial void OntopSectionChanging(System.Nullable<int> value);
    partial void OntopSectionChanged();
    partial void OnsectionOrderChanging(System.Nullable<int> value);
    partial void OnsectionOrderChanged();
    partial void OnrootSectionChanging(System.Nullable<byte> value);
    partial void OnrootSectionChanged();
    partial void OnsectionDisabledChanging(System.Nullable<byte> value);
    partial void OnsectionDisabledChanged();
    partial void OnsectionurlChanging(string value);
    partial void OnsectionurlChanged();
    partial void Onsectionurl2Changing(string value);
    partial void Onsectionurl2Changed();
    partial void Onsectionurl3Changing(string value);
    partial void Onsectionurl3Changed();
    partial void OnsectionHeaderChanging(string value);
    partial void OnsectionHeaderChanged();
    partial void OnsectionHeader2Changing(string value);
    partial void OnsectionHeader2Changed();
    partial void OnsectionHeader3Changing(string value);
    partial void OnsectionHeader3Changed();
    partial void OnsectionDescriptionChanging(string value);
    partial void OnsectionDescriptionChanged();
    partial void OnsectionDescription2Changing(string value);
    partial void OnsectionDescription2Changed();
    partial void OnsectionDescription3Changing(string value);
    partial void OnsectionDescription3Changed();
    partial void OnsTitleChanging(string value);
    partial void OnsTitleChanged();
    partial void OnsMetaDescChanging(string value);
    partial void OnsMetaDescChanged();
    #endregion
		
		public section()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sectionID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int sectionID
		{
			get
			{
				return this._sectionID;
			}
			set
			{
				if ((this._sectionID != value))
				{
					this.OnsectionIDChanging(value);
					this.SendPropertyChanging();
					this._sectionID = value;
					this.SendPropertyChanged("sectionID");
					this.OnsectionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sectionName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string sectionName
		{
			get
			{
				return this._sectionName;
			}
			set
			{
				if ((this._sectionName != value))
				{
					this.OnsectionNameChanging(value);
					this.SendPropertyChanging();
					this._sectionName = value;
					this.SendPropertyChanged("sectionName");
					this.OnsectionNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sectionName2", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string sectionName2
		{
			get
			{
				return this._sectionName2;
			}
			set
			{
				if ((this._sectionName2 != value))
				{
					this.OnsectionName2Changing(value);
					this.SendPropertyChanging();
					this._sectionName2 = value;
					this.SendPropertyChanged("sectionName2");
					this.OnsectionName2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sectionName3", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string sectionName3
		{
			get
			{
				return this._sectionName3;
			}
			set
			{
				if ((this._sectionName3 != value))
				{
					this.OnsectionName3Changing(value);
					this.SendPropertyChanging();
					this._sectionName3 = value;
					this.SendPropertyChanged("sectionName3");
					this.OnsectionName3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sectionWorkingName", DbType="NVarChar(255)")]
		public string sectionWorkingName
		{
			get
			{
				return this._sectionWorkingName;
			}
			set
			{
				if ((this._sectionWorkingName != value))
				{
					this.OnsectionWorkingNameChanging(value);
					this.SendPropertyChanging();
					this._sectionWorkingName = value;
					this.SendPropertyChanged("sectionWorkingName");
					this.OnsectionWorkingNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sectionImage", DbType="NVarChar(255)")]
		public string sectionImage
		{
			get
			{
				return this._sectionImage;
			}
			set
			{
				if ((this._sectionImage != value))
				{
					this.OnsectionImageChanging(value);
					this.SendPropertyChanging();
					this._sectionImage = value;
					this.SendPropertyChanged("sectionImage");
					this.OnsectionImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_topSection", DbType="Int")]
		public System.Nullable<int> topSection
		{
			get
			{
				return this._topSection;
			}
			set
			{
				if ((this._topSection != value))
				{
					this.OntopSectionChanging(value);
					this.SendPropertyChanging();
					this._topSection = value;
					this.SendPropertyChanged("topSection");
					this.OntopSectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sectionOrder", DbType="Int")]
		public System.Nullable<int> sectionOrder
		{
			get
			{
				return this._sectionOrder;
			}
			set
			{
				if ((this._sectionOrder != value))
				{
					this.OnsectionOrderChanging(value);
					this.SendPropertyChanging();
					this._sectionOrder = value;
					this.SendPropertyChanged("sectionOrder");
					this.OnsectionOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rootSection", DbType="TinyInt")]
		public System.Nullable<byte> rootSection
		{
			get
			{
				return this._rootSection;
			}
			set
			{
				if ((this._rootSection != value))
				{
					this.OnrootSectionChanging(value);
					this.SendPropertyChanging();
					this._rootSection = value;
					this.SendPropertyChanged("rootSection");
					this.OnrootSectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sectionDisabled", DbType="TinyInt")]
		public System.Nullable<byte> sectionDisabled
		{
			get
			{
				return this._sectionDisabled;
			}
			set
			{
				if ((this._sectionDisabled != value))
				{
					this.OnsectionDisabledChanging(value);
					this.SendPropertyChanging();
					this._sectionDisabled = value;
					this.SendPropertyChanged("sectionDisabled");
					this.OnsectionDisabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sectionurl", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string sectionurl
		{
			get
			{
				return this._sectionurl;
			}
			set
			{
				if ((this._sectionurl != value))
				{
					this.OnsectionurlChanging(value);
					this.SendPropertyChanging();
					this._sectionurl = value;
					this.SendPropertyChanged("sectionurl");
					this.OnsectionurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sectionurl2", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string sectionurl2
		{
			get
			{
				return this._sectionurl2;
			}
			set
			{
				if ((this._sectionurl2 != value))
				{
					this.Onsectionurl2Changing(value);
					this.SendPropertyChanging();
					this._sectionurl2 = value;
					this.SendPropertyChanged("sectionurl2");
					this.Onsectionurl2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sectionurl3", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string sectionurl3
		{
			get
			{
				return this._sectionurl3;
			}
			set
			{
				if ((this._sectionurl3 != value))
				{
					this.Onsectionurl3Changing(value);
					this.SendPropertyChanging();
					this._sectionurl3 = value;
					this.SendPropertyChanged("sectionurl3");
					this.Onsectionurl3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sectionHeader", DbType="NVarChar(MAX)")]
		public string sectionHeader
		{
			get
			{
				return this._sectionHeader;
			}
			set
			{
				if ((this._sectionHeader != value))
				{
					this.OnsectionHeaderChanging(value);
					this.SendPropertyChanging();
					this._sectionHeader = value;
					this.SendPropertyChanged("sectionHeader");
					this.OnsectionHeaderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sectionHeader2", DbType="NVarChar(MAX)")]
		public string sectionHeader2
		{
			get
			{
				return this._sectionHeader2;
			}
			set
			{
				if ((this._sectionHeader2 != value))
				{
					this.OnsectionHeader2Changing(value);
					this.SendPropertyChanging();
					this._sectionHeader2 = value;
					this.SendPropertyChanged("sectionHeader2");
					this.OnsectionHeader2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sectionHeader3", DbType="NVarChar(MAX)")]
		public string sectionHeader3
		{
			get
			{
				return this._sectionHeader3;
			}
			set
			{
				if ((this._sectionHeader3 != value))
				{
					this.OnsectionHeader3Changing(value);
					this.SendPropertyChanging();
					this._sectionHeader3 = value;
					this.SendPropertyChanged("sectionHeader3");
					this.OnsectionHeader3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sectionDescription", DbType="NVarChar(MAX)")]
		public string sectionDescription
		{
			get
			{
				return this._sectionDescription;
			}
			set
			{
				if ((this._sectionDescription != value))
				{
					this.OnsectionDescriptionChanging(value);
					this.SendPropertyChanging();
					this._sectionDescription = value;
					this.SendPropertyChanged("sectionDescription");
					this.OnsectionDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sectionDescription2", DbType="NVarChar(MAX)")]
		public string sectionDescription2
		{
			get
			{
				return this._sectionDescription2;
			}
			set
			{
				if ((this._sectionDescription2 != value))
				{
					this.OnsectionDescription2Changing(value);
					this.SendPropertyChanging();
					this._sectionDescription2 = value;
					this.SendPropertyChanged("sectionDescription2");
					this.OnsectionDescription2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sectionDescription3", DbType="NVarChar(MAX)")]
		public string sectionDescription3
		{
			get
			{
				return this._sectionDescription3;
			}
			set
			{
				if ((this._sectionDescription3 != value))
				{
					this.OnsectionDescription3Changing(value);
					this.SendPropertyChanging();
					this._sectionDescription3 = value;
					this.SendPropertyChanged("sectionDescription3");
					this.OnsectionDescription3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sTitle", DbType="NVarChar(255)")]
		public string sTitle
		{
			get
			{
				return this._sTitle;
			}
			set
			{
				if ((this._sTitle != value))
				{
					this.OnsTitleChanging(value);
					this.SendPropertyChanging();
					this._sTitle = value;
					this.SendPropertyChanged("sTitle");
					this.OnsTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sMetaDesc", DbType="NVarChar(255)")]
		public string sMetaDesc
		{
			get
			{
				return this._sMetaDesc;
			}
			set
			{
				if ((this._sMetaDesc != value))
				{
					this.OnsMetaDescChanging(value);
					this.SendPropertyChanging();
					this._sMetaDesc = value;
					this.SendPropertyChanged("sMetaDesc");
					this.OnsMetaDescChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
